export const MAX_TIME = 210; /*seconds */
export let iconsEasy = [
  '<i class="fa-solid fa-bell" data.index = "0"></i>',
  '<i class="fa-solid fa-anchor" data.index = "1"></i>',
  '<i class="fa-solid fa-bicycle" data.index = "2"></i>',
  '<i class="fa-brands fa-btc" data.index = "3"></i>',
  '<i class="fa-solid fa-cannabis" data.index = "4"></i>',
  '<i class="fa-solid fa-candy-cane"></i>',
  '<i class="fa-solid fa-camera"></i>',
  '<i class="fa-solid fa-cloud"></i>',
];

export let iconsMedium = [
  '<i class="fa-solid fa-bell"></i>',
  '<i class="fa-solid fa-anchor"></i>',
  '<i class="fa-solid fa-bicycle"></i>',
  '<i class="fa-brands fa-btc"></i>',
  '<i class="fa-solid fa-cannabis"></i>',
  '<i class="fa-solid fa-candy-cane"></i>',
  '<i class="fa-solid fa-camera"></i>',
  '<i class="fa-solid fa-cloud"></i>',
  '<i class="fa-solid fa-battery-full"></i>',
  '<i class="fa-solid fa-chess-rook"></i>',
  '<i class="fa-solid fa-coins"></i>',
  '<i class="fa-solid fa-cube"></i>',
  '<i class="fa-solid fa-dharmachakra"></i>',
  '<i class="fa-solid fa-dice-d20"></i>',
  '<i class="fa-solid fa-dna"></i>',
  '<i class="fa-solid fa-dragon"></i>',
  '<i class="fa-solid fa-earth-europe"></i>',
  '<i class="fa-brands fa-ethereum"></i>',
];

export let iconsHard = [
  '<i class="fa-solid fa-bell"></i>',
  '<i class="fa-solid fa-anchor"></i>',
  '<i class="fa-solid fa-bicycle"></i>',
  '<i class="fa-brands fa-btc"></i>',
  '<i class="fa-solid fa-cannabis"></i>',
  '<i class="fa-solid fa-candy-cane"></i>',
  '<i class="fa-solid fa-camera"></i>',
  '<i class="fa-solid fa-cloud"></i>',
  '<i class="fa-solid fa-battery-full"></i>',
  '<i class="fa-solid fa-chess-rook"></i>',
  '<i class="fa-solid fa-coins"></i>',
  '<i class="fa-solid fa-cube"></i>',
  '<i class="fa-solid fa-dharmachakra"></i>',
  '<i class="fa-solid fa-dice-d20"></i>',
  '<i class="fa-solid fa-dna"></i>',
  '<i class="fa-solid fa-dragon"></i>',
  '<i class="fa-solid fa-earth-europe"></i>',
  '<i class="fa-brands fa-ethereum"></i>',
  '<i class="fa-solid fa-eye"></i>',
  '<i class="fa-solid fa-feather-pointed"></i>',
  '<i class="fa-solid fa-fish-fins"></i>',
  '<i class="fa-brands fa-fort-awesome"></i>',
  '<i class="fa-solid fa-football"></i>',
  '<i class="fa-solid fa-gas-pump"></i>',
  '<i class="fa-solid fa-globe"></i>',
  '<i class="fa-solid fa-gun"></i>',
  '<i class="fa-solid fa-heart-pulse"></i>',
  '<i class="fa-brands fa-hotjar"></i>',
  '<i class="fa-solid fa-hourglass"></i>',
  '<i class="fa-solid fa-jet-fighter"></i>',
  '<i class="fa-solid fa-section"></i>',
  '<i class="fa-solid fa-tractor"></i>',
];
